### ISSUE TITLE
Out of memory with RTX 5090

### ISSUE THREAD

**Issue by merecesarchviz** [Fantasy-AMAP/fantasy-talking#17]
I can´t run with the minimin settings get out of vram, any tipo to run on 32GB VRAM?

**Comment by wangqiang9** [comment]
Do you try [infer_24G.sh](https://github.com/Fantasy-AMAP/fantasy-talking/blob/main/infer_24G.sh) ?

**Comment by vedant0321** [comment]
I attempted to run the infer.sh script using an NVIDIA L4 GPU with 24 GB VRAM and 60 GB RAM. I also specified **torch_dtype=torch.float8_e4m3fn**  and  **set num_persistent_param_in_dit=0**, but I am still encountering a "CUDA out of memory" error.

**Comment by merecesarchviz** [comment]
yes, i give up and I´m using the comfyui node from kijai where he implemented it on it.

**Comment by johndpope** [comment]
just oberservation - the t5 model from google (with wan) is like 10gb
https://github.com/Fantasy-AMAP/fantasy-talking/blob/070f0d47b05da2ae8313b269f7a2a05d249e2595/infer.py#L144

i did some wrangling to shuffling it to cpu / computer ram here
https://github.com/johndpope/OmniHuman-1-hack/tree/main/seaweed_apt

text to video WAN T2V  (as of 30th april 25)  is ridiculously hungry for vram - you basically either need to shuffle the model in and out of gpu - or have 2 gpus - one just for the text stuff or 
in my file here - i eagerly up front compute the text embedding for the t5 - and then seperately pass it into the wan model https://github.com/johndpope/OmniHuman-1-hack/blob/main/seaweed_apt/generate.py
(this was exploratory work to do 4 step diffusion generation but when i read WAN paper they actually have already achieved this)

but image to video i2v with wan can perform well on much less gpu resources - check civitai.com / wan models. 
(unrelated - I've been waiting on my 5090 preorder since January)

**Comment by FurkanGozukara** [comment]
it is working no issues i am developing 1-click installer

but it is slow due to being Wan based

it can work as low as i presume like 8/10 GB GPUs

**Comment by aliok222** [comment]
> it is working no issues i am developing 1-click installer and improved app
> 
> but it is slow due to being Wan based
> 
> it can work as low as i presume like 8/10 GB GPUs

Hi, where one click Sir ?

**Comment by FurkanGozukara** [comment]
> > it is working no issues i am developing 1-click installer and improved app
> > but it is slow due to being Wan based
> > it can work as low as i presume like 8/10 GB GPUs
> 
> Hi, where one click Sir ?

so sorry it took huge time to add all these features

more features coming tomorrow hopefully

installers and app > https://www.patreon.com/posts/127855145

![Image](https://github.com/user-attachments/assets/cc61e4a1-6dd1-4681-897b-81f134472437)

**Comment by sebastianzehner** [comment]
I am using the RTX 4090 with 24GB VRAM and had the same problem but changed the **app.py** and now it works for me.

```
parser.add_argument(
    "--num_persistent_param_in_dit",
    type=int,
    #default=None,
    default=7000000000,
    required=False,
    help="Maximum parameter quantity retained in video memory, small number to reduce VRAM required",
)
```

**Comment by SoftologyPro** [comment]
> I am using the RTX 4090 with 24GB VRAM and had the same problem but changed the **app.py** and now it works for me.
> 
> ```
> parser.add_argument(
>     "--num_persistent_param_in_dit",
>     type=int,
>     #default=None,
>     default=7000000000,
>     required=False,
>     help="Maximum parameter quantity retained in video memory, small number to reduce VRAM required",
> )
> ```

Can you share your complete edited app.py?  Adding just that parameter into ap.py gives me this error when run...

```
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --num_persistent_param_in_dit: conflicting option string: --num_persistent_param_in_dit
```

@FurkanGozukara you can help too if you want to help rather than paywall your installer again :)

**Comment by sebastianzehner** [comment]
> Can you share your complete edited app.py? Adding just that parameter into app.py gives me this error when run...
> 
> ```
>     raise ArgumentError(action, message % conflict_string)
> argparse.ArgumentError: argument --num_persistent_param_in_dit: conflicting option string: --num_persistent_param_in_dit
> ```
> 
> [@FurkanGozukara](https://github.com/FurkanGozukara) you can help too if you want to help rather than just advertise your paywalled installer again :)

You have to search for this part `--num_persistent_param_in_dit` in the **app.py** and then change the default value from `None` to `7000000000`. That's it.

**Comment by SoftologyPro** [comment]
> > Can you share your complete edited app.py? Adding just that parameter into app.py gives me this error when run...
> > ```
> >     raise ArgumentError(action, message % conflict_string)
> > argparse.ArgumentError: argument --num_persistent_param_in_dit: conflicting option string: --num_persistent_param_in_dit
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [@FurkanGozukara](https://github.com/FurkanGozukara) you can help too if you want to help rather than just advertise your paywalled installer again :)
> 
> You have to search for this part `--num_persistent_param_in_dit` in the **app.py** and then change the default value from `None` to `7000000000`. That's it.

Thanks, that works.  But still takes arounf 20 minutes for the default example image and wav.  Is that the same for you?

**Comment by sebastianzehner** [comment]
> Thanks, that works. But still takes around 20 minutes for the default example image and wav on a 4090. Is that the same for you?

Yes, about 18 minutes for a 4-second clip here too. That’s expected based on the detailed table on GitHub - around 32.8s/it and 20GB VRAM usage.

**Comment by SoftologyPro** [comment]
> > Thanks, that works. But still takes around 20 minutes for the default example image and wav on a 4090. Is that the same for you?
> 
> Yes, about 18 minutes for a 4-second clip here too. That’s expected based on the detailed table on GitHub - around 32.8s/it and 20GB VRAM usage.

OK thanks.  For anyone else you also need ffprobe.exe and ffmpeg.exe in the same directory as app.py for it to work.
Then it does finish, but only uses the first 4 seconds of audio (after 18 minutes of processing).

**Comment by SoftologyPro** [comment]
If you want to do this sort of animate face with sound processing on consumer GPUs I recommend SadTalker.
It took a total of 1m11s to create this result from the same image and sound and uses the full sound file.

https://github.com/user-attachments/assets/0714e352-5edb-4bda-be43-87b574efbbe1

**Comment by sebastianzehner** [comment]
I'm on Linux, and yeah - 4 seconds just isn't enough. I'd love to get results with 6 to 8 seconds; that would be much better. Next, I’ll give it a shot with ComfyUI.

I also tried SadTalker, but the quality was underwhelming - barely any face or body movement, and the teeth looked pretty weird.

**Comment by LSI86** [comment]
in gradio environment it doesn't work, if I set default=7000000000, (or 0), after a few seconds it stops working "Connection errored out."
(RTX 3070 8GB VRAM) I would even wait if it worked :( Console dump:
C:\tmp\gradio\5493f900ed6a5784e4dcf8bcb3787e43329707fa12c7c2b8e2baaf47eb9036f5\woman.png
Namespace(wan_model_dir='./models/Wan2.1-I2V-14B-720P', fantasytalking_model_path='./models/fantasytalking_model.ckpt', wav2vec_model_dir='./models/wav2vec2-base-960h', image_path='C:/tmp/gradio/5493f900ed6a5784e4dcf8bcb3787e43329707fa12c7c2b8e2baaf47eb9036f5/woman.png', audio_path='C:/tmp/gradio/b30e4ee55d2106601af6b32171b7980b661f198e4702d8ee200f71926ebf9f42/woman.wav', prompt='woman talking', output_dir='output', image_size=512, audio_scale=1.0, prompt_cfg_scale=5.0, audio_cfg_scale=5.0, max_num_frames=81, inference_steps=20, fps=23, num_persistent_param_in_dit=7000000000, seed=1247)
Loading models from: ['./models/Wan2.1-I2V-14B-720P/diffusion_pytorch_model-00001-of-00007.safetensors', './models/Wan2.1-I2V-14B-720P/diffusion_pytorch_model-00002-of-00007.safetensors', './models/Wan2.1-I2V-14B-720P/diffusion_pytorch_model-00003-of-00007.safetensors', './models/Wan2.1-I2V-14B-720P/diffusion_pytorch_model-00004-of-00007.safetensors', './models/Wan2.1-I2V-14B-720P/diffusion_pytorch_model-00005-of-00007.safetensors', './models/Wan2.1-I2V-14B-720P/diffusion_pytorch_model-00006-of-00007.safetensors', './models/Wan2.1-I2V-14B-720P/diffusion_pytorch_model-00007-of-00007.safetensors']

**Comment by aliok222** [comment]
hi

If you would use original Wan 2.1 model at 60GB is likely the full 14B parameter version in high precision , really heavy , and quantized models are not as “precise” or expressive as the original full-precision models, so the best choice is Sonic the best so far 

Thx

**Comment by aliok222** [comment]
> > > it is working no issues i am developing 1-click installer and improved app
> > > but it is slow due to being Wan based
> > > it can work as low as i presume like 8/10 GB GPUs
> > 
> > 
> > Hi, where one click Sir ?
> 
> so sorry it took huge time to add all these features
> 
> more features coming tomorrow hopefully
> 
> installers and app > https://www.patreon.com/posts/127855145
> 
> ![Image](https://github.com/user-attachments/assets/cc61e4a1-6dd1-4681-897b-81f134472437)

hi

If you would use original Wan 2.1 model at 60GB is likely the full 14B parameter version in high precision , really heavy, and quantized models are not as “precise” or expressive as the original full-precision models, so the best choice is Sonic the best so far

Thx

**Comment by aliok222** [comment]
> I can´t run with the minimin settings get out of vram, any tipo to run on 32GB VRAM?

Use Sonic it not worth to use put you GPU under pressure and stress 

Good luck

**Comment by SoftologyPro** [comment]
> > I can´t run with the minimin settings get out of vram, any tipo to run on 32GB VRAM?
> 
> Use Sonic it not worth to use put you GPU under pressure and stress 
> 
> Good luck  

Can you provide a link for Sonic?

**Comment by aliok222** [comment]
> > > I can´t run with the minimin settings get out of vram, any tipo to run on 32GB VRAM?
> > 
> > 
> > Use Sonic it not worth to use put you GPU under pressure and stress
> > Good luck
> 
> Can you provide a link for Sonic?

https://github.com/smthemex/ComfyUI_Sonic

**Comment by SoftologyPro** [comment]
> > > > I can´t run with the minimin settings get out of vram, any tipo to run on 32GB VRAM?
> > > 
> > > 
> > > Use Sonic it not worth to use put you GPU under pressure and stress
> > > Good luck
> > 
> > 
> > Can you provide a link for Sonic?
> 
> https://github.com/smthemex/ComfyUI_Sonic

Thanks.  That does not seem to combine the audio with the animation though at the last step.  It is much faster.  This is the end result of their example.  It animates the init image with the audio, but does not combine the audio with the animation.

https://github.com/user-attachments/assets/157fc13f-1111-4aa0-ab01-c132f4b95b77
